### ISSUE TITLE
Info about video clip experiment

### ISSUE THREAD

**Issue by srikanth-sfu** [makarandtapaswi/MovieQA_CVPR2016#1]
Hi @makarandtapaswi ,

You mentioned in your paper that you learn embeddings between shots and "sentences" using the ranking loss method from zhu et al. ICCV 15 paper pre-trained on movie description dataset.

1. Can you elaborate more on how you do this? Which data source do you use from the text side? 

2. Or else can you release the code and trained model you used to compute these embeddings?

Thanks

**Comment by makarandtapaswi** [comment]
Hi

We train our text and vision embeddings on the DVS dataset (http://www.mpi-inf.mpg.de/departments/computer-vision-and-multimodal-computing/research/vision-and-language/mpii-movie-description-dataset/).

In more detail, we train RNNs on the DVS sentences to obtain a text embedding. Simultaneously, we run feature extraction on images (GoogLeNet, Places205CNN) from video shots. We further learn a linear embedding from image features to text space to perform cosine similarity comparison. The training objective is a kind of ranking, i.e. an aligned sentence-video pair should score (rank) higher than other pairs.

This is quite similar to the model in DeViSE (research.google.com/pubs/archive/41473.pdf) except of course we have video (multiple frames) and a sentence (multiple words).

Hope that helps!

**Comment by srikanth-sfu** [comment]
How do you select negatives?

**Comment by makarandtapaswi** [comment]
Need to look for it, we took this from Yukun's previous paper about aligning books with movies ;)

**Comment by YknZhu** [comment]
The negative (contrastive pairs) are randomly chosen from unaligned DVS video / sentences.
